name: test if we can create a new app
description: Compiles and caches all code into the dist folder
inputs:
  node-version:
    description: The node version to use for the module.
    default: '16.x'
  angular-version:
    description: The angular version to use for the module.
    default: '12'
runs:
  using: 'composite'
  steps:
    - name: Setup Node, retrieve node_modules and dist folder from cache
      uses: ./.github/build-artifacts
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup angular project and run all tests
      uses: actions/setup-node@v2
      env:
        CI: true
        NG_CLI_ANALYTICS: false false
        npm_config_legacy_peer_dependencies: true
        npm_config_legacy_peer_deps: true
        npm_config_force: true
    - name: set up verdaccio
      uses: verdaccio/github-actions/publish@v0.1.0
      with:
        args: -d
    - name : Test if angular builds using local register
      shell: bash
      run: |
        npm set registry http://localhost:4873
        # log into it
        npx npm-cli-login -u testuser -p testPass -e test@example.com -r http://localhost:4873
        npx tsc -p ./tools/tsconfig.tools.json
        cp tools/package.json dist/tools
        node ./dist/tools/publishLocal.js
        cd ~
        npx  @angular/cli@${{ inputs.angular-version }} new demo --skip-git  --routing --style css --minimal --strict
        cd demo
        npx ng update @angular/cli --migrate-only --from 12.0.0 --to 12.0.1 --allow-dirty
        npx ng g m home --route home --module app.module
        npx ng g m about --route about --module app.module
        echo installing updated Rx
        npm i rxjs@7  --legacy-peer-deps --force
        npx ng add @scullyio/init --renderer puppeteer --skip-confirmation
        npx ng g @scullyio/init:blog
        npx ng build
        npx scully --noPrompt
