name: NewProject

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm i @nrwl/workspace -g
      - run: nx run-many --target=build --all --prod
      - run: npm run symlinks
      - run: nx g @nrwl/angular:app test-app
      - run: nx g @scullyio/init:install -- --project=test-app --verbose
      - run: nx build test-app
      - run: node ./dist/libs/scully/scully --project=test-app
        env:
          CI: true
