name: NewProject

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npx nx run-many --target=build --all --prod
      - run: npm run symlinks
      - run: npx nx g @nrwl/angular:app testapp --style=css --routing
      - run: npm run build --prefix libs/scully-schematics/
      - run: npx nx g ./libs/scully-schematics/src/collection.json:ng-add --project=testapp --pluginTS=false
      - run: npx nx build testapp
      - run: node ./dist/libs/scully/src/scully.js --project=testapp
        env:
          CI: true
